(ns projetos-clojure.mes1052)
(def x (read))
(cond
  (= x 1) (println "January")
  (= x 2) (println "February")
  (= x 3) (println "March")
  (= x 4) (println "April")
  (= x 5) (println "May")
  (= x 6) (println "June")
  (= x 7) (println "July")
  (= x 8) (println "August")
  (= x 9) (println "September")
  (= x 10) (println "October")
  (= x 11) (println "November")
  (= x 12) (println "December")
)